version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules:/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - your-hyperledger-network # Reference the custom network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - your-hyperledger-network # Reference the custom network

networks:
  your-hyperledger-network: # Define your custom network
    external: true # Make it an external network, use the name of your Hyperledger Fabric network
