version: '3'
services:
  backend:
    image: brahim98/devops_project_back:MySpringimage
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MyDB?useSSL=false
      SPRING_DATASOURCE_USERNAME: brahim
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - mysql

  frontend:
    image: brahim98/devops_project_front:MyAngularimage
    ports:
      - "8084:8084"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: MyDB
      MYSQL_USER: brahim
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
