version: '3'
services:
  backend:
    image: brahim98/devops_project_back:MySpringimage
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/MyDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: brahim
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    image: brahim98/devops_project_front:MyAngularimage
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  nginx-exporter:
    image: "nginx/nginx-prometheus-exporter:latest"
    command: ["-nginx.scrape-uri=http://frontend:80/metrics"]  # Adjust this command
    ports:
      - "9113:9113"
    depends_on:
      - frontend  # Depend on the frontend service
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: MyDB
      MYSQL_USER: brahim
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
