global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

# This is where you have simple alert rules
rule_files:
  - ./alertmanager/alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'all-targets'  # You can use a common job name for all targets
    metrics_path: /metrics  # Adjust the metrics path if needed
    static_configs:
      - targets: ['192.168.33.10:9113', '192.168.33.10:8082']
    
